### ISSUE TITLE
Create a PUT request to update a todo

### ISSUE THREAD

**Issue by i-am-popo** [i-am-popo/CRUD-API#4]

**Comment by tamalbag117** [comment]
please assign me 
https://github.com/i-am-popo/CRUD-API/issues/1
https://github.com/i-am-popo/CRUD-API/issues/2
https://github.com/i-am-popo/CRUD-API/issues/3
https://github.com/i-am-popo/CRUD-API/issues/4

**Comment by Ishikasaraf20** [comment]
hey @i-am-popo can you assign this issue to me i can work on it
